site_name: Kootstrap
site_description: Kootstrap is a bootstrap to Keras. It is a technique of compile and loading a datasets into a Keras application by means of a few initial instructions that enable the introduction of the rest of the program from an input device.
pages:
    - Home: 'index.md'
    - Crawler: 'crawler/index.md'
    - Compiler: 'compiler/index.md'
    - Trainer: 'trainer/index.md'
    - Tester: 'tester/index.md'
    - Analyzer: 'analyzer/index.md'
    - About:
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/release-notes.md'
theme: readthedocs
site_author: 'Glauco Roberto Munsberg'
site_url: 'http://www.glaucomunsberg.com/'